### ISSUE TITLE
lamp_simple is incompatible with CentOS 7

### ISSUE THREAD

**Issue by varnav** [ansible/ansible-examples#119]
Hello!

One of incompatibilities was fixed by https://github.com/ansible/ansible-examples/pull/118 - but two remain:

1. There is no mysql-server package in the default repo
2. There is no iptables service, it was replaced by firewalld

This can be fixed easily, and I can do this, but that will make this example incompatible with CentOS earlier than 7. Is it worth doing this?

**Comment by varnav** [comment]
Also SElinux seems to be blocking PHP from connecting to MySQL DB.

**Comment by gregdek** [comment]
Should probably be a separate Centos 7 example...

**Comment by pypingou** [comment]
Can't you check which version of CentOS it is?

**Comment by varnav** [comment]
# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

If you ok with that, I will make separate lamp_simple example for CentOS 7 and will make a merge request then. Should be quite simple.

**Comment by gregdek** [comment]
I think a separate C7 demo would be useful.

**Comment by varnav** [comment]
New PR created: https://github.com/ansible/ansible-examples/pull/121

I've tested it on 2 machines with fresh CentOS 7.1 installs

**Comment by varnav** [comment]
PR merged, new Centos7/RHEL7 specific example added to examples.
