### ISSUE TITLE
Issues with wordpress-nginx

### ISSUE THREAD

**Issue by varnav** [ansible/ansible-examples#123]
I'm making a RHEL7 adaptation of wordpress-nginx, and I see two issues:

- Nginx restart fails, because there is a duplicate line

`Listen 80 default_server`

in nginx.conf and /conf.d/default.conf
I believe this affects not only RHEL 7 but earlier versions too.

- SElinux keeps blocking nginx, you will get 403 forbidden if SElinux is enabled.

**Comment by gregdek** [comment]
I'd recommend a patch for wordpress-nginx duplicate line... 

...but for SELinux, not sure there's much we can/should do. We don't want to be defining SELinux policy in a simple example like this; we should probably just note somewhere in the example that it may conflict with pre-existing SELinux policies.

If someone comes up with a simple fix to the SELinux problem, of course we're happy to merge.

**Comment by varnav** [comment]
There doesn't seem to be a simple SELinux policy in this case.

**Comment by gregdek** [comment]
Then it may not be the best case of an example -- or you can make it clear in the documentation that SELinux must be turned off for this example to work.

**Comment by TechIsCool** [comment]
I have submitted a pull #127  for a rhel7 version of wordpress. Let me know if you have any questions. SElinux is enabled and functional.
