### ISSUE TITLE
ansible/tomcat 

### ISSUE THREAD

**Issue by gbane2012** [ansible/ansible-examples#139]
I am having error message at the last step (wait_for )

fatal: [webserver1]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "invocation": {"module_args": {"connect_timeout": 5, "delay": "10", "exclude_hosts": null, "host": "127.0.0.1", "path": null, "port": "8080", "search_regex": null, "state": "started", "timeout": 300}, "module_name": "wait_for"}, "msg": "Timeout when waiting for 127.0.0.1:8080"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @mmc.retry

**Comment by thisdavejohnson** [comment]
This isn't an error with the playbook. The wait_for is timing out and therefore, failing. You should check that port 8080 indeed becomes available, extend the timeout, or ignore the error and proceed, depending on your particular use case.
