### ISSUE TITLE
lamp_simple_rhel7 fails on SELinux and firewalld

### ISSUE THREAD

**Issue by boyvanduuren** [ansible/ansible-examples#145]
The playbook failed on me running the `Configure ntp file` task in common, this is due to the `libselinux-python` package not installed on both hosts.
Also, there is an issue with `firewalld` not present on minimal install CentOS7 machine, which causes the playbook to fail.
Please see my pull request (https://github.com/ansible/ansible-examples/pull/146) which fixes both issues.

**Comment by varnav** [comment]
We had a short firewalld discussion here:
https://github.com/ansible/ansible-examples/pull/141#issuecomment-202752693
BTW I think your fixes are good and should be merged.

**Comment by varnav** [comment]
Fixes seem to be merged, can we close this?

**Comment by boyvanduuren** [comment]
Of course :+1:
