### ISSUE TITLE
No defaults/main.yml example, trying to create one but can't get it to work

### ISSUE THREAD

**Issue by coryfklein** [ansible/ansible-examples#152]
I'd like to add an example showing how [Role Default Variables](http://docs.ansible.com/ansible/playbooks_roles.html#role-default-variables) work by creating a `defaults/main.yml` file for a role.

The docs say:

> Role default variables allow you to set default variables for included or dependent roles (see below). To create defaults, simply add a defaults/main.yml file in your role directory. These variables will have the lowest priority of any variables available, and can be easily overridden by any other variable, including inventory variables.

In [this short and simple commit](https://github.com/coryfklein/ansible-examples/commit/106894cb82fe36482740ff7014b8bef07f3d767c), I set up a playbook that should print out the value of a default variable, but instead it fails with the error:

> fatal: [localhost] => One or more undefined variables: 'myvar' is undefined

This can be reproduced like so:

```
git clone git@github.com:coryfklein/ansible-examples.git
cd ansible-examples/debug_default_vars
./reproduce_problem.sh
```

I clearly must be missing a required step. I'd like to know what that step is so I can additionally submit a PR to the [documentation for this feature](https://github.com/ansible/ansible/blob/devel/docsite/rst/playbooks_roles.rst#role-default-variables) so other new users like me don't experience the same frustration in getting this to work.

**Comment by MichaelBaydoun** [comment]
You invoked as a task instead of a role. See comment on your commit.

**Comment by coryfklein** [comment]
I incorporated your advice [here](https://github.com/coryfklein/ansible-examples/commit/f875e7f61cea87c03e776e85426a5a72f9738727).

Now I'm getting the error `ERROR: hosts declaration is required`.

\*sigh\* I'm sorry, my newb-ness is showing here. The error doesn't make sense to me, I'm clearly declaring the host as `localhost`.

**Comment by coryfklein** [comment]
I believe I resolved that issue with another commit, now I'm working on `ERROR: tasks is not a legal parameter in an Ansible task or handler`.

**Comment by coryfklein** [comment]
...aand the problem is resolved. Thanks @MichaelBaydoun .
