### ISSUE TITLE
Ticket Monster JBoss application

### ISSUE THREAD

**Issue by NickHeiner** [ansible/ansible-examples#164]
I have successfully used the JBoss playbook to deploy the hello world app to an ec2 node. I can see it on port `8080`. How can I see the ticket monster app? Where in the playbook is it configured that the hello world app comes up instead of the ticket monster app on `8080`?

Here's what I see on `8080`: 

![image](https://cloud.githubusercontent.com/assets/829827/17451322/db053190-5b33-11e6-9813-6ab55e5aab21.png)

Thanks!

**Comment by thisdavejohnson** [comment]
Per the README:

The HelloWorld application will be available at http://<jboss server>:<http_port>/helloworld

The Ticket Monster application will be available at http://<jboss server>:<http_port>/ticket-monster
