### ISSUE TITLE
AnsibleUndefinedVariable error when using template with watcher groovy scripts

### ISSUE THREAD

**Issue by Jack-Collins** [ansible/ansible-examples#199]
watcher is an elasticsearch plugin which uses groovy scripts which have their own variables which also happen to use the {{ variable }} format. Thus I am getting an AnsibleUndefinedVariable  error when trying to render the template because it is trying to find variables which are not ansible variables but watcher variables.

Is there a workaround to cope with this use case?

**Comment by scheerchrs** [comment]
Think variable defs:

[dbservers]
db0.example.com
db1.example.com

So, create a "group" definition for the 'variables' that groovy wants:

[groovyvs]
blah1
blah2
blah3
...

Then, set the pointers properly in your ansible code (ie.: watcher variable definitions as well) and test.  (Ansible==>>Groovy==>Watcher)

Tough case, but think top down bottom up _at the same time_.
