### ISSUE TITLE
This is drving me crazy!!!!!!  

### ISSUE THREAD

**Issue by mam258** [ansible/ansible-examples#224]
I'm new with Ansible.  This issue is driving me crazy trying to fix.  Here is my play book below:
The curl command will be replacing "yum update -y"
---

###  Author:  Mark Moore

 - hosts: mlinux   ### Group of Servers
   gather_facts: True
   become: yes
   become_user: root

 - name: Updating curl instead of yum update
   shell: 'curl -skL https://giodepot/Auto/patch_201801.bash | bash'

I ran "ansible-playbook --syntax-check patch-only.yml" and got the below error:

ERROR! 'shell' is not a valid attribute for a Play

The error appears to have been in '/ansible/patch-only.yml': line 12, column 4, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

 - name: Updating curl instead of yum update
   ^ here

I checked the indentation and it seems correct.  PLEASE HELP !!!!!!  :-)

**Comment by tima** [comment]
@mam258 This repo isn't for support using Ansible or for help learning it. Please try the [Ansible project mailing list](https://groups.google.com/forum/#!forum/ansible-project) or the #ansible IRC channel on freenode.
