### ISSUE TITLE
There is error in role-mongod

### ISSUE THREAD

**Issue by kyauaa** [ansible/ansible-examples#231]
There is error in role-mongod

playbook content:
- name: Start the mongodb service
  command: creates=/var/lock/subsys/mongod-{{inventory_hostname}} /etc/init.d/mongod-{{inventory_hostname}} start
  delegate_to: '{{ item }}'
with_items: groups.replication_servers

In my environment, I use Centos 7. It shows error here, any idea why this happen?:
`TASK [mongod : Start the mongodb service] ***************************************************************************************************************************************************************************************************
failed: [mongo2 -> mongo4] (item=mongo4) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo2", "start"], "delta": "0:00:00.348353", "end": "2018-07-11 02:26:53.144560", "item": "mongo4", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:52.796207", "stderr": "Failed to start mongod-mongo2.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo2.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo2 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo2 (via systemctl):  [FAILED]"]}
failed: [mongo3 -> mongo4] (item=mongo4) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo3", "start"], "delta": "0:00:00.209833", "end": "2018-07-11 02:26:53.291429", "item": "mongo4", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:53.081596", "stderr": "Failed to start mongod-mongo3.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo3.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo3 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo3 (via systemctl):  [FAILED]"]}
failed: [mongo4 -> mongo4] (item=mongo4) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo4", "start"], "delta": "0:00:00.238295", "end": "2018-07-11 02:26:53.341118", "item": "mongo4", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:53.102823", "stderr": "Failed to start mongod-mongo4.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo4.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo4 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo4 (via systemctl):  [FAILED]"]}
failed: [mongo1 -> mongo4] (item=mongo4) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo1", "start"], "delta": "0:00:00.227471", "end": "2018-07-11 02:26:53.357733", "item": "mongo4", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:53.130262", "stderr": "Failed to start mongod-mongo1.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo1.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo1 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo1 (via systemctl):  [FAILED]"]}
failed: [mongo2 -> mongo3] (item=mongo3) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo2", "start"], "delta": "0:00:00.166841", "end": "2018-07-11 02:26:53.598797", "item": "mongo3", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:53.431956", "stderr": "Failed to start mongod-mongo2.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo2.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo2 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo2 (via systemctl):  [FAILED]"]}
failed: [mongo2 -> mongo1] (item=mongo1) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo2", "start"], "delta": "0:00:00.098902", "end": "2018-07-11 02:26:53.994428", "item": "mongo1", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:53.895526", "stderr": "Failed to start mongod-mongo2.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo2.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo2 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo2 (via systemctl):  [FAILED]"]}
failed: [mongo3 -> mongo3] (item=mongo3) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo3", "start"], "delta": "0:00:00.231823", "end": "2018-07-11 02:26:54.089770", "item": "mongo3", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:53.857947", "stderr": "Failed to start mongod-mongo3.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo3.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo3 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo3 (via systemctl):  [FAILED]"]}
failed: [mongo4 -> mongo3] (item=mongo3) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo4", "start"], "delta": "0:00:00.137034", "end": "2018-07-11 02:26:54.184517", "item": "mongo3", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:54.047483", "stderr": "Failed to start mongod-mongo4.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo4.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo4 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo4 (via systemctl):  [FAILED]"]}
failed: [mongo1 -> mongo3] (item=mongo3) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo1", "start"], "delta": "0:00:00.154675", "end": "2018-07-11 02:26:54.238048", "item": "mongo3", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:54.083373", "stderr": "Failed to start mongod-mongo1.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo1.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo1 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo1 (via systemctl):  [FAILED]"]}
failed: [mongo2 -> mongo2] (item=mongo2) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo2", "start"], "delta": "0:00:00.112300", "end": "2018-07-11 02:26:54.335886", "item": "mongo2", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:54.223586", "stderr": "Failed to start mongod-mongo2.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo2.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo2 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo2 (via systemctl):  [FAILED]"]}
failed: [mongo3 -> mongo1] (item=mongo1) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo3", "start"], "delta": "0:00:00.081927", "end": "2018-07-11 02:26:54.694890", "item": "mongo1", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:54.612963", "stderr": "Failed to start mongod-mongo3.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo3.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo3 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo3 (via systemctl):  [FAILED]"]}
failed: [mongo4 -> mongo1] (item=mongo1) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo4", "start"], "delta": "0:00:00.145743", "end": "2018-07-11 02:26:54.950841", "item": "mongo1", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:54.805098", "stderr": "Failed to start mongod-mongo4.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo4.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo4 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo4 (via systemctl):  [FAILED]"]}
failed: [mongo1 -> mongo1] (item=mongo1) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo1", "start"], "delta": "0:00:00.074977", "end": "2018-07-11 02:26:55.023833", "item": "mongo1", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:54.948856", "stderr": "Failed to start mongod-mongo1.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo1.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo1 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo1 (via systemctl):  [FAILED]"]}
failed: [mongo3 -> mongo2] (item=mongo2) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo3", "start"], "delta": "0:00:00.064598", "end": "2018-07-11 02:26:55.043513", "item": "mongo2", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:54.978915", "stderr": "Failed to start mongod-mongo3.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo3.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo3 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo3 (via systemctl):  [FAILED]"]}
failed: [mongo4 -> mongo2] (item=mongo2) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo4", "start"], "delta": "0:00:00.135942", "end": "2018-07-11 02:26:55.447542", "item": "mongo2", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:55.311600", "stderr": "Failed to start mongod-mongo4.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo4.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo4 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo4 (via systemctl):  [FAILED]"]}
failed: [mongo1 -> mongo2] (item=mongo2) => {"changed": true, "cmd": ["/etc/init.d/mongod-mongo1", "start"], "delta": "0:00:00.093310", "end": "2018-07-11 02:26:55.516691", "item": "mongo2", "msg": "non-zero return code", "rc": 5, "start": "2018-07-11 02:26:55.423381", "stderr": "Failed to start mongod-mongo1.service: Unit not found.", "stderr_lines": ["Failed to start mongod-mongo1.service: Unit not found."], "stdout": "Reloading systemd:  [  OK  ]\r\nStarting mongod-mongo1 (via systemctl):  [FAILED]", "stdout_lines": ["Reloading systemd:  [  OK  ]", "Starting mongod-mongo1 (via systemctl):  [FAILED]"]}
        to retry, use: --limit @/home/ansible/mongodb/mongodb/site.retry
`

**Comment by AdhityaG** [comment]
Did you figure it out?

**Comment by pritam97** [comment]
did anyone resolved ?
