### ISSUE TITLE
Wrong file name

### ISSUE THREAD

**Issue by alexander-rebello** [ansible/ansible-examples#310]
Hi, I noticed in the repo "ansible-examples" in folder "/wordpress-nginx/group_vars/" there is a file called "all" altough it should have the file extention of a yml file e.g. "all.yml". I didn't check if thats the case in other repos.

**Comment by BachenbergS** [comment]
This is no bug. Ansible supports multiple file formats as inventory source: https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#inventory-basics-formats-hosts-and-groups
