### ISSUE TITLE
Namenode format fails

### ISSUE THREAD

**Issue by subrotosanyal** [ansible/ansible-examples#35]
While executing: ansible-playbook -vvvv -i hosts site.yml

I end up encountering:
<pre>
TASK: [Format the namenode] *************************************************** 
<ec2-50-16-176-201.compute-1.amazonaws.com> ESTABLISH CONNECTION FOR USER: subroto
<ec2-50-16-176-201.compute-1.amazonaws.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/subroto/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'ec2-50-16-176-201.compute-1.amazonaws.com', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1384258178.59-209258933647175 && chmod a+rx $HOME/.ansible/tmp/ansible-1384258178.59-209258933647175 && echo $HOME/.ansible/tmp/ansible-1384258178.59-209258933647175'"]
<ec2-50-16-176-201.compute-1.amazonaws.com> REMOTE_MODULE command creates=/usr/lib/hadoop/namenode.formatted su - hdfs -c "hadoop namenode -format" && touch /usr/lib/hadoop/namenode.formatted #USE_SHELL
<ec2-50-16-176-201.compute-1.amazonaws.com> PUT /var/folders/4w/yr852nyj3dbd1qj4w6qcwtqm0000gn/T/tmpkJz6kN TO /root/.ansible/tmp/ansible-1384258178.59-209258933647175/command
<ec2-50-16-176-201.compute-1.amazonaws.com> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/subroto/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', 'ec2-50-16-176-201.compute-1.amazonaws.com', "/bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1384258178.59-209258933647175/command; rm -rf /root/.ansible/tmp/ansible-1384258178.59-209258933647175/ >/dev/null 2>&1'"]
failed: [ec2-50-16-176-201.compute-1.amazonaws.com] => {"changed": true, "cmd": " su - hdfs -c \"hadoop namenode -format\" && touch /usr/lib/hadoop/namenode.formatted ", "delta": "0:00:04.824282", "end": "2013-11-12 07:09:45.620571", "item": "", "rc": 1, "start": "2013-11-12 07:09:40.796289"}
stderr: DEPRECATED: Use of this script to execute hdfs command is deprecated.
Instead use the hdfs command for it.

13/11/12 07:09:42 INFO namenode.NameNode: STARTUP_MSG: 
/************************************************************
STARTUP_MSG: Starting NameNode
STARTUP_MSG:   host = ip-10-143-182-148/10.143.182.148
STARTUP_MSG:   args = [-format]
STARTUP_MSG:   version = 2.0.0-cdh4.4.0
STARTUP_MSG:   classpath = /etc/hadoop/conf:/usr/lib/hadoop/lib/protobuf-java-2.4.0a.jar:/usr/lib/hadoop/lib/xmlenc-0.52.jar:/usr/lib/hadoop/lib/jasper-runtime-5.5.23.jar:/usr/lib/hadoop/lib/jline-0.9.94.jar:/usr/lib/hadoop/lib/commons-codec-1.4.jar:/usr/lib/hadoop/lib/jsp-api-2.1.jar:/usr/lib/hadoop/lib/commons-logging-1.1.1.jar:/usr/lib/hadoop/lib/guava-11.0.2.jar:/usr/lib/hadoop/lib/jasper-compiler-5.5.23.jar:/usr/lib/hadoop/lib/commons-io-2.1.jar:/usr/lib/hadoop/lib/jackson-mapper-asl-1.8.8.jar:/usr/lib/hadoop/lib/commons-digester-1.8.jar:/usr/lib/hadoop/lib/paranamer-2.3.jar:/usr/lib/hadoop/lib/avro-1.7.4.jar:/usr/lib/hadoop/lib/junit-4.8.2.jar:/usr/lib/hadoop/lib/zookeeper-3.4.5-cdh4.4.0.jar:/usr/lib/hadoop/lib/servlet-api-2.5.jar:/usr/lib/hadoop/lib/snappy-java-1.0.4.1.jar:/usr/lib/hadoop/lib/jackson-jaxrs-1.8.8.jar:/usr/lib/hadoop/lib/jackson-xc-1.8.8.jar:/usr/lib/hadoop/lib/commons-lang-2.5.jar:/usr/lib/hadoop/lib/jets3t-0.6.1.jar:/usr/lib/hadoop/lib/jersey-core-1.8.jar:/usr/lib/hadoop/lib/slf4j-api-1.6.1.jar:/usr/lib/hadoop/lib/asm-3.2.jar:/usr/lib/hadoop/lib/jettison-1.1.jar:/usr/lib/hadoop/lib/jersey-json-1.8.jar:/usr/lib/hadoop/lib/commons-net-3.1.jar:/usr/lib/hadoop/lib/commons-math-2.1.jar:/usr/lib/hadoop/lib/xz-1.0.jar:/usr/lib/hadoop/lib/jackson-core-asl-1.8.8.jar:/usr/lib/hadoop/lib/jetty-6.1.26.cloudera.2.jar:/usr/lib/hadoop/lib/commons-beanutils-core-1.8.0.jar:/usr/lib/hadoop/lib/stax-api-1.0.1.jar:/usr/lib/hadoop/lib/commons-cli-1.2.jar:/usr/lib/hadoop/lib/commons-beanutils-1.7.0.jar:/usr/lib/hadoop/lib/jsch-0.1.42.jar:/usr/lib/hadoop/lib/mockito-all-1.8.5.jar:/usr/lib/hadoop/lib/jetty-util-6.1.26.cloudera.2.jar:/usr/lib/hadoop/lib/jsr305-1.3.9.jar:/usr/lib/hadoop/lib/commons-httpclient-3.1.jar:/usr/lib/hadoop/lib/commons-configuration-1.6.jar:/usr/lib/hadoop/lib/commons-el-1.0.jar:/usr/lib/hadoop/lib/jaxb-api-2.2.2.jar:/usr/lib/hadoop/lib/kfs-0.3.jar:/usr/lib/hadoop/lib/log4j-1.2.17.jar:/usr/lib/hadoop/lib/commons-collections-3.2.1.jar:/usr/lib/hadoop/lib/commons-compress-1.4.1.jar:/usr/lib/hadoop/lib/activation-1.1.jar:/usr/lib/hadoop/lib/jersey-server-1.8.jar:/usr/lib/hadoop/lib/slf4j-log4j12-1.6.1.jar:/usr/lib/hadoop/lib/jaxb-impl-2.2.3-1.jar:/usr/lib/hadoop/.//hadoop-annotations.jar:/usr/lib/hadoop/.//hadoop-common-2.0.0-cdh4.4.0-tests.jar:/usr/lib/hadoop/.//hadoop-common.jar:/usr/lib/hadoop/.//hadoop-common-2.0.0-cdh4.4.0.jar:/usr/lib/hadoop/.//hadoop-annotations-2.0.0-cdh4.4.0.jar:/usr/lib/hadoop/.//hadoop-auth.jar:/usr/lib/hadoop/.//hadoop-auth-2.0.0-cdh4.4.0.jar:/usr/lib/hadoop-hdfs/./:/usr/lib/hadoop-hdfs/lib/protobuf-java-2.4.0a.jar:/usr/lib/hadoop-hdfs/lib/xmlenc-0.52.jar:/usr/lib/hadoop-hdfs/lib/jasper-runtime-5.5.23.jar:/usr/lib/hadoop-hdfs/lib/jline-0.9.94.jar:/usr/lib/hadoop-hdfs/lib/commons-codec-1.4.jar:/usr/lib/hadoop-hdfs/lib/jsp-api-2.1.jar:/usr/lib/hadoop-hdfs/lib/commons-logging-1.1.1.jar:/usr/lib/hadoop-hdfs/lib/guava-11.0.2.jar:/usr/lib/hadoop-hdfs/lib/commons-io-2.1.jar:/usr/lib/hadoop-hdfs/lib/jackson-mapper-asl-1.8.8.jar:/usr/lib/hadoop-hdfs/lib/zookeeper-3.4.5-cdh4.4.0.jar:/usr/lib/hadoop-hdfs/lib/commons-daemon-1.0.3.jar:/usr/lib/hadoop-hdfs/lib/servlet-api-2.5.jar:/usr/lib/hadoop-hdfs/lib/commons-lang-2.5.jar:/usr/lib/hadoop-hdfs/lib/jersey-core-1.8.jar:/usr/lib/hadoop-hdfs/lib/asm-3.2.jar:/usr/lib/hadoop-hdfs/lib/jackson-core-asl-1.8.8.jar:/usr/lib/hadoop-hdfs/lib/jetty-6.1.26.cloudera.2.jar:/usr/lib/hadoop-hdfs/lib/commons-cli-1.2.jar:/usr/lib/hadoop-hdfs/lib/jetty-util-6.1.26.cloudera.2.jar:/usr/lib/hadoop-hdfs/lib/jsr305-1.3.9.jar:/usr/lib/hadoop-hdfs/lib/commons-el-1.0.jar:/usr/lib/hadoop-hdfs/lib/log4j-1.2.17.jar:/usr/lib/hadoop-hdfs/lib/jersey-server-1.8.jar:/usr/lib/hadoop-hdfs/.//hadoop-hdfs-2.0.0-cdh4.4.0-tests.jar:/usr/lib/hadoop-hdfs/.//hadoop-hdfs.jar:/usr/lib/hadoop-hdfs/.//hadoop-hdfs-2.0.0-cdh4.4.0.jar:/usr/lib/hadoop-yarn/.//*:/usr/lib/hadoop-0.20-mapreduce/./:/usr/lib/hadoop-0.20-mapreduce/lib/protobuf-java-2.4.0a.jar:/usr/lib/hadoop-0.20-mapreduce/lib/xmlenc-0.52.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jasper-runtime-5.5.23.jar:/usr/lib/hadoop-0.20-mapreduce/lib/hsqldb-1.8.0.10.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jline-0.9.94.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-codec-1.4.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jsp-api-2.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-logging-1.1.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/guava-11.0.2.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jasper-compiler-5.5.23.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-io-2.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/avro-compiler-1.7.4.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jackson-mapper-asl-1.8.8.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-digester-1.8.jar:/usr/lib/hadoop-0.20-mapreduce/lib/paranamer-2.3.jar:/usr/lib/hadoop-0.20-mapreduce/lib/avro-1.7.4.jar:/usr/lib/hadoop-0.20-mapreduce/lib/junit-4.8.2.jar:/usr/lib/hadoop-0.20-mapreduce/lib/zookeeper-3.4.5-cdh4.4.0.jar:/usr/lib/hadoop-0.20-mapreduce/lib/servlet-api-2.5.jar:/usr/lib/hadoop-0.20-mapreduce/lib/snappy-java-1.0.4.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jackson-jaxrs-1.8.8.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jackson-xc-1.8.8.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-lang-2.5.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jets3t-0.6.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jersey-core-1.8.jar:/usr/lib/hadoop-0.20-mapreduce/lib/slf4j-api-1.6.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/asm-3.2.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jettison-1.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jersey-json-1.8.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-net-3.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-math-2.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/xz-1.0.jar:/usr/lib/hadoop-0.20-mapreduce/lib/hadoop-fairscheduler-2.0.0-mr1-cdh4.4.0.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jackson-core-asl-1.8.8.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jetty-6.1.26.cloudera.2.jar:/usr/lib/hadoop-0.20-mapreduce/lib/kfs-0.2.2.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-beanutils-core-1.8.0.jar:/usr/lib/hadoop-0.20-mapreduce/lib/stax-api-1.0.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-cli-1.2.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-beanutils-1.7.0.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jsch-0.1.42.jar:/usr/lib/hadoop-0.20-mapreduce/lib/mockito-all-1.8.5.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jetty-util-6.1.26.cloudera.2.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jsr305-1.3.9.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-httpclient-3.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/ant-contrib-1.0b3.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-configuration-1.6.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-el-1.0.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jaxb-api-2.2.2.jar:/usr/lib/hadoop-0.20-mapreduce/lib/kfs-0.3.jar:/usr/lib/hadoop-0.20-mapreduce/lib/log4j-1.2.17.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-collections-3.2.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/commons-compress-1.4.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/activation-1.1.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jersey-server-1.8.jar:/usr/lib/hadoop-0.20-mapreduce/lib/jaxb-impl-2.2.3-1.jar:/usr/lib/hadoop-0.20-mapreduce/.//hadoop-core-2.0.0-mr1-cdh4.4.0.jar:/usr/lib/hadoop-0.20-mapreduce/.//hadoop-test-2.0.0-mr1-cdh4.4.0.jar:/usr/lib/hadoop-0.20-mapreduce/.//hadoop-ant.jar:/usr/lib/hadoop-0.20-mapreduce/.//hadoop-core.jar:/usr/lib/hadoop-0.20-mapreduce/.//hadoop-examples.jar:/usr/lib/hadoop-0.20-mapreduce/.//hadoop-examples-2.0.0-mr1-cdh4.4.0.jar:/usr/lib/hadoop-0.20-mapreduce/.//hadoop-ant-2.0.0-mr1-cdh4.4.0.jar:/usr/lib/hadoop-0.20-mapreduce/.//hadoop-tools.jar:/usr/lib/hadoop-0.20-mapreduce/.//hadoop-test.jar:/usr/lib/hadoop-0.20-mapreduce/.//hadoop-tools-2.0.0-mr1-cdh4.4.0.jar
STARTUP_MSG:   build = file:///data/1/jenkins/workspace/generic-package-rhel64-6-0/topdir/BUILD/hadoop-2.0.0-cdh4.4.0/src/hadoop-common-project/hadoop-common -r c0eba6cd38c984557e96a16ccd7356b7de835e79; compiled by 'jenkins' on Tue Sep  3 19:33:17 PDT 2013
STARTUP_MSG:   java = 1.6.0_24
************************************************************/
13/11/12 07:09:42 INFO namenode.NameNode: registered UNIX signal handlers for [TERM, HUP, INT]
13/11/12 07:09:45 FATAL conf.Configuration: error parsing conf mapred-site.xml
java.io.FileNotFoundException: /etc/hadoop/conf.empty/mapred-site.xml (Permission denied)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:140)
	at java.io.FileInputStream.<init>(FileInputStream.java:96)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:87)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:178)
	at java.net.URL.openStream(URL.java:1031)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:1873)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:1944)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:1897)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:1815)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:712)
	at org.apache.hadoop.conf.Configuration.getTrimmed(Configuration.java:731)
	at org.apache.hadoop.conf.Configuration.getLong(Configuration.java:949)
	at org.apache.hadoop.security.Groups.<init>(Groups.java:62)
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:182)
	at org.apache.hadoop.security.UserGroupInformation.initUGI(UserGroupInformation.java:252)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:223)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:214)
	at org.apache.hadoop.security.UserGroupInformation.isSecurityEnabled(UserGroupInformation.java:277)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:730)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1128)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1233)
13/11/12 07:09:45 FATAL namenode.NameNode: Exception in namenode join
java.lang.RuntimeException: java.io.FileNotFoundException: /etc/hadoop/conf.empty/mapred-site.xml (Permission denied)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2042)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:1897)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:1815)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:712)
	at org.apache.hadoop.conf.Configuration.getTrimmed(Configuration.java:731)
	at org.apache.hadoop.conf.Configuration.getLong(Configuration.java:949)
	at org.apache.hadoop.security.Groups.<init>(Groups.java:62)
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:182)
	at org.apache.hadoop.security.UserGroupInformation.initUGI(UserGroupInformation.java:252)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:223)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:214)
	at org.apache.hadoop.security.UserGroupInformation.isSecurityEnabled(UserGroupInformation.java:277)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:730)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1128)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1233)
Caused by: java.io.FileNotFoundException: /etc/hadoop/conf.empty/mapred-site.xml (Permission denied)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:140)
	at java.io.FileInputStream.<init>(FileInputStream.java:96)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:87)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:178)
	at java.net.URL.openStream(URL.java:1031)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:1873)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:1944)
	... 14 more
13/11/12 07:09:45 INFO util.ExitUtil: Exiting with status 1
13/11/12 07:09:45 INFO namenode.NameNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at ip-10-143-182-148/10.143.182.148
************************************************************/

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/subroto/site.retry
</pre>

Further the file permissions in conf.empty folder looks like this:
<pre>[root@ip-10-143-182-148 ~]# ls -l /etc/hadoop/conf.empty
total 60
-rw-r--r-- 1 root root 1335 Sep  3 22:48 configuration.xsl
-rw-r--r-- 1 root root 1001 Nov 12 07:03 core-site.xml
-rw-r--r-- 1 root root 2489 Nov 12 07:03 hadoop-metrics.properties
-rw-r--r-- 1 root root 1773 Nov 12 07:03 hadoop-metrics2.properties
-rw-r--r-- 1 root root 9196 Sep  3 22:48 hadoop-policy.xml
-rw-r--r-- 1 root root 3730 Nov 12 07:03 hdfs-site.xml
-rw-r--r-- 1 root root 8735 Sep  3 22:48 log4j.properties
-rw------- 1 root root 3752 Nov 12 07:03 mapred-site.xml
-rw-r--r-- 1 root root  125 Nov 12 07:03 slaves
-rw-r--r-- 1 root root 2316 Sep  3 22:48 ssl-client.xml.example
-rw-r--r-- 1 root root 2251 Sep  3 22:48 ssl-server.xml.example</pre>

**Comment by bcoca** [comment]
closing as the hadoop example was removed
