### ISSUE TITLE
ansible-examples/lamp_simple - fails on selinux (says it's disabled)

### ISSUE THREAD

**Issue by aalbertson** [ansible/ansible-examples#40]
I presume this is a relic of these playbooks not being ready for 1.3x but I receive the following error when I try to run this playbook:

failed: [[REDACTED IP]] => {"failed": true, "item": ""}
msg: SELinux is disabled on this host.

This happens for all hosts I'm running this against.

**Comment by Hubbitus** [comment]
It will not work.

getenforce always return 0 exit code and text representation of SELinux status:

```
# getenforce ; echo $?
Permissive
0
```
# getenforce ; echo $?
Enforcing
0

For such check selinuxenabled should be used.
