### ISSUE TITLE
lamp_simple does not work with chef/centos-6.5 in vagrant

### ISSUE THREAD

**Issue by austinpray** [ansible/ansible-examples#82]
https://vagrantcloud.com/chef/centos-6.5

```
TASK: [common | Configure ntp file] ******************************************* 
failed: [default] => {"failed": true}
msg: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
```

**Comment by ivy001** [comment]
You can insert the following before the ''- name: insert iptables rule for http" line in .../roles/web/install_httpd.yml 

- name: Create file if not exist 
  file: path=/etc/sysconfig/iptables mode=0644 state=touch
 
This will ensure the file is present before the next task
